travis:
  secure:
    BINSTAR_TOKEN: IFDQ5aRGJ5nM6clF/s1c9ZKCYpXV0mRm03Ju/ENmhALOEbKPGHQ6Vqhg26lAaVtdjXDUQ3IMkUoitW0e220Ry3VvvCB52PB4s0+OUypqvQnP5IEJ9IcsNJRgJAB8Uu8bWcumHcWVzF6aK+HaK/wgsKIO5LLoMbDVHw0sKvvR4lzEOsIJAuHwy0oPLLpa3LH5iHrDiymYfMhX/c++AGFTLHH+UFZEEYvdIRub+oAZQyX/R72DH02hTw1zaWvrDb0dZo4VR4v/NUnNxbE+QPu5z4ockwX9Jg/vJvQweRlZm1cnyPAs8qFwNKL+TFyUb5vyE5eVQZQUWiqz9ISbJ9A061YW+t7R3AIGy6MsKRAbhbD8vMFk/A9Yiejh/slWPew5yrngXHLAQV68t8y8igNyNKIC+thSnWBqtP3T12m08xT3rTMpB3nybmEi4NDEQmA8KKXb1mpiBUkWTtyHU1I9RpBaxPNwJMDt4OHbyZi1P9U+2PCnX2j6mierpJf2hZuoVkDYLWkzQ7EIG7Bjng+G6hwS+i0Dm/CXyQAysYJsDZyUI42P6zO0CsV/WZbJmas2OZ1McYhemkBkFW3z/6GP5MUSQoPnN2R7J8vXEYl8EFleGvbI09N2nNRn5t3ts7haeoLKEBIXYihhrLjIj3bej6iOB5GuznuUT15DrgXsV7Y=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
